### ISSUE TITLE
Change in render() method - why?

### ISSUE THREAD

**Issue by kpeck71** [learn-co-curriculum/redux-dispatch-with-event-listeners#9]
Why is the render method changed to:
function render(){
  document.setInnerHtml = state.count
}

Shouldn't it stay as 
function render(){
    let container = document.getElementById('container');
    container.textContent = state.count;
}

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @kpeck71 .

We have updated the materials so that the code snippets are consistent and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
